version: '3.8'

services:  
    db-fatboar:
        image: mariadb:latest
        restart: always        
        env_file:
            - .env.docker
        volumes:
            - /app/data:/var/lib/mysql
        networks: 
            - db-nw

    api:
        build: 
            context: .
            dockerfile: ./fatboar-api/Dockerfile
        ports:
            - "3000:3000"
        env_file:
            - .env.docker
        networks:
            - apps-nw
            - db-nw

    front: 
        build: 
            context: .
            dockerfile: ./fatboar-concours/Dockerfile
        ports:
            - "4200:4200"
        networks:
            - apps-nw  

networks:
    apps-nw:
    db-nw:
